### ISSUE TITLE
Where to put custom CKEditor plugins?

### ISSUE THREAD

**Issue by dmarko484** [alump/CKEditor#1]
Hello, we were using ckeditor-wrapper addon with Vaadin 7 ... and now, as a part of  Vaadin 8 migration process, we would like to use your ckeditor addon as its Vaadin 8 compatible. But we are not sure where to put custom ckeditor plugins? Former addon had plugin directory inside a widgetset, but cant find something like this in your addon. Any hint here, please?

**Comment by alump** [comment]
Original idea was that you can do similar class CKEditorTextField is. Where you extend the AbstractCKEditorTextField and have your own @JavaScript annotation with reference to your addon .js file. And this file should be located to same package as your class is (eg. the vaadin-save-plugin.js is in same package as CkEditorTextField is).

**Comment by alump** [comment]
See current demo project. I added there example plugin and how to use it.
