### ISSUE TITLE
When writing in CKEditor cursor jumps to the beginning of first row after /?v-uiId=0 is called

### ISSUE THREAD

**Issue by standam** [alump/CKEditor#3]
Vaadin 8.0.6 - after each /vaadinServlet/UIDL/?v-uiId=0 call cursor jumps to the start of the line while writting. Do you know what that can caused? As a response the call sends something like that:
![image](https://user-images.githubusercontent.com/982932/27133561-da68a548-5112-11e7-828b-0cefc5822619.png)

**Comment by alump** [comment]
What is causing the UIDL call on your application?

I tested with UI poll and with Push enabled, could not make cursor to jump. Using UI polling will cause client to notify server about new value, but unless application logic after that call setValue it should not cause cursor to jump.

**Comment by alump** [comment]
If possible please compile current version here at GitHub (master branch) and test it with your application. There was one issue I found, but not sure if helps you. I will release it as soon as it's tested, if it helps.

**Comment by standam** [comment]
Can you point me out how to compile code from GitHub, don't have an experience with that.?

**Comment by standam** [comment]
I've found out, that it is caused by addPollListener, which updates Label value at top layout every 10 sec.
![image](https://user-images.githubusercontent.com/982932/27386080-f25c20e4-5694-11e7-98d6-7c9b91b48150.png)

**Comment by alump** [comment]
My fix is now also out, 0.1.2 hopefully helps with issues like this.

**Comment by daulet2030** [comment]
Hi, the issue is back if I use binder with the ckeditor field. Because of binder every time changeVariables is fired the cursor position is reset

**Comment by sascha-broich** [comment]
After some Stacktrace-Evaluation it seems to me that the problem is Vaadin's poor handling of setComponentError. 
On every ValueChangeEvent the Binder calls field.setComponentError(null). And in there is a markAsDirty() call, which leads to a paintContent call which disturbs the editor.
A simple solution should be to overwrite the setComponentError method where first a check is performed to determine whether the error requires a markAsDirty (and the fireComponentErrorEvent) or not:

```java
public void setComponentError(ErrorMessage componentError) {
  ErrorMessage oldError=getComponentError();
  if(oldError!=componentError && (oldError==null || !oldError.equals(componentError))) {
    super.setComponentError(componentError);
  }
}	
```
