### ISSUE TITLE
HTTPS security is compromised 

### ISSUE THREAD

**Issue by SimonC-24** [alump/CKEditor#7]
Any suggestion how can I resolve 'HTTPS security is compromised by http://cdn.ckeditor.com/4.6.2/standard/ckeditor.js' error? Ckeditor does not load on https.

Cheers, Simon

**Comment by SimonC-24** [comment]
The same warning in Chrome
'The page at 'https://xyz' was loaded over HTTPS, but requested an insecure script 'http://cdn.ckeditor.com/4.6.2/standard/ckeditor.js'. This request has been blocked; the content must be served over HTTPS.'

**Comment by alump** [comment]
0.1.2 is now using HTTPS address to load ckeditor.js from their website. Hopefully this fixes the issue.

**Comment by SimonC-24** [comment]
It works, thanks for update 0.1.2.
